### ISSUE TITLE
Test data for two additional Macs

### ISSUE THREAD

**Issue by MichaelDays** [XiongjieDai/GPU-Benchmarks-on-LLM-Inference#1]
I ran some tests with Llama2 🦙🦙 on the two Macs I have access to, running with llama.cpp as of 24th Aug 2023 (main commit 335acd2ffd7b04501c6d8773ab9fcee6e7bf8639).

Feel free to include them if you would like to. ;)

| GPU | Model | eval time |     |     | prompt eval time |     |     | mean eval time | mean prompt eval time |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Mac Pro (2019 intel/16 core/384Gbyte) CPU | 7B_q4_0| 54.78 | 61.74 | 59.77 | 35.72 | 37.29 | 35.88 | 58.76 | 36.30 |
| | 13B_q4_0 | 102.20 | 101.97 | 100.26 | 63.28 | 62.77 | 62.93 | 101.48 | 62.99 |
| | 70B_q4_0 | 547.89 | 456.45 | 457.12 | 295.31 | 296.16 | 295.12 | 487.15 | 295.53 |
| M2 Mini Pro (12/19/32) CPU | 7B_q4_0 | 48.04 | 45.78 | 49.61 | 17.34 | 16.81 | 16.82 | 47.81 | 16.99 |
| | 13B_q4_0 | 75.93 | 72.56 | 71.66 | 29.39 | 28.50 | 28.46 | 73.38 | 28.78 |
| | 70B_q4_0 | 225956.54 | OOM | OOM | 27220.19 | OOM | OOM | OOM | OOM |
| | 7B.f16 | 118.10 | 116.46 | 118.95 | 17.11 | 16.62 | 17.84 | 117.84 | 17.19 |
| M2 Mini Pro (12/19/32) GPU | 7B_q4_0 | 28.92 | 28.54 | 29.27 | 5.89 | 5.95 | 5.86 | 28.91 | 5.90 |
| | 13B_q4_0 | 50.76 | 50.71 | 50.63 | 10.30 | 10.29 | 10.28 | 50.70 | 10.29 |
| | 70B_q4_0 | OOM | OOM | OOM | OOM | OOM | OOM | OOM | OOM |
| | 7B.f16 | 92.43 | 91.91 | 92.11 | 5.56 | 5.53 | 5.56 | 92.15 | 5.55 |

**Comment by XiongjieDai** [comment]
> 

Include them in the appendix! Thanks for your data point ❤️

**Comment by XiongjieDai** [comment]
> I ran some tests with Llama2 🦙🦙 on the two Macs I have access to, running with llama.cpp as of 24th Aug 2023 (main commit 335acd2ffd7b04501c6d8773ab9fcee6e7bf8639).
> 
> Feel free to include them if you would like to. ;)
> 
> GPU	Model	eval time			prompt eval time			mean eval time	mean prompt eval time
> Mac Pro (2019 intel/16 core/384Gbyte) CPU	7B_q4_0	54.78	61.74	59.77	35.72	37.29	35.88	58.76	36.30
> 13B_q4_0	102.20	101.97	100.26	63.28	62.77	62.93	101.48	62.99
> 70B_q4_0	547.89	456.45	457.12	295.31	296.16	295.12	487.15	295.53
> M2 Mini Pro (12/19/32) CPU	7B_q4_0	48.04	45.78	49.61	17.34	16.81	16.82	47.81	16.99
> 13B_q4_0	75.93	72.56	71.66	29.39	28.50	28.46	73.38	28.78
> 70B_q4_0	225956.54	OOM	OOM	27220.19	OOM	OOM	OOM	OOM
> 7B.f16	118.10	116.46	118.95	17.11	16.62	17.84	117.84	17.19
> M2 Mini Pro (12/19/32) GPU	7B_q4_0	28.92	28.54	29.27	5.89	5.95	5.86	28.91	5.90
> 13B_q4_0	50.76	50.71	50.63	10.30	10.29	10.28	50.70	10.29
> 70B_q4_0	OOM	OOM	OOM	OOM	OOM	OOM	OOM	OOM
> 7B.f16	92.43	91.91	92.11	5.56	5.53	5.56	92.15	5.55

Include them in the appendix! Thanks for your data point ❤️
