### ISSUE TITLE
Include a version of lab to Llamma 3 for the RTX 3060 (12Gb)

### ISSUE THREAD

**Issue by Pablo-Oliveira** [XiongjieDai/GPU-Benchmarks-on-LLM-Inference#10]
You can include a version of Llamma 3 for the RTX 3060 (12Gb)?
I'm having trouble implementing the official version.
The walkthrough is broken.

**Comment by XiongjieDai** [comment]
Hi, the walkthrough script should be fixed now. Let me know if you need any help!

**Comment by XiongjieDai** [comment]
Solved.
