### ISSUE TITLE
Which GPU benchmark you would like to see?

### ISSUE THREAD

**Issue by XiongjieDai** [XiongjieDai/GPU-Benchmarks-on-LLM-Inference#11]
I am currently working on the GPU benchmark on LLaMA 3; let me know what GPU combination benchmark from [Runpod](https://www.runpod.io/console/deploy) you would like to see! 🤗

**Comment by XiongjieDai** [comment]
Right now, I'm planning to test the following NVIDIA GPUs:

3070 8GB
3080 10GB
3080 Ti 12GB
4070 Ti 12GB
4080 16GB
RTX 4000 Ada 20GB
3090 24GB
4090 24GB
RTX 5000 Ada 32GB
3090 24GB * 2
4090 24GB * 2
RTX A6000 48GB
RTX 6000 Ada 48GB
RTX 4000 Ada 20GB * 4
A100 PCIe 80GB
A100 SXM 80GB
H100 PCIe 80GB
H100 SXM 80GB
3090 24GB * 4
4090 24GB * 4
RTX 5000 Ada 32GB * 4
3090 24GB * 6
4090 24GB * 8
RTX A6000 48GB * 4
RTX 6000 Ada 48GB * 4
A100 PCIe 80GB * 4
A100 SXM 80GB * 4
H100 PCIe 80GB * 4
H100 SXM 80GB * 4

**Comment by joennlae** [comment]
First of all great repo :-) Fantastic information.

If I could wish, I would like to see the serverless options compared:

4090 24GB ~ _24 GB GPU PRO_
A6000 48 GB ~ _48 GB GPU_
A6000 48 GB * 2 ~ _48 GB GPU_
A40 48 GB ~ _48 GB GPU_
A40 48 GB * 2 ~ _48 GB GPU_
A6000 Ada 48 GB ~ _48 GB GPU PRO_
L40 48 GB ~ _48 GB GPU PRO_
A100 80 GB ~ _80 GB GPU_
H100 80 GB ~ _80 GB GPU PRO_


![Screenshot 2024-05-08 at 21 13 03](https://github.com/XiongjieDai/GPU-Benchmarks-on-LLM-Inference/assets/1493766/73153e77-a8e4-451b-9c3e-445bca479ea1)

In the best case, we could also compare it with Mixtral8x7B or with a comparable MoE.

Just some thoughts :-) But feel free to ignore them :-)

**Comment by adriangalilea** [comment]
I'm interested in the performance of the mac studio with tons of RAM, so I would love to see more of em :)

I would love to see a 128gb mac studio also, I guess that's hard to find, but just in case.

**Comment by XiongjieDai** [comment]
@joennlae Thank you for your suggestions! I can add A40 and L40 to the benchmarks.😁

For the benchmark on MoE, the idea behind MoE is total active params. Mixtral8x7B can access 47B parameters but only uses 13B active parameters during inference. You can think about it as having the same VRAM requirement and prompt possessing speed as a 47B model, but the generating text speed is like a 13B model performance.

I ran the benchmark on my M2 Ultra Mac Studio. I guess this can prove the idea if you compare the results with different sizes of LLaMA 3 models. I probably would not introduce another pipeline for MoE in benchmark this time. I hope the benchmark on LLaMA 3 is still helpful to you :-)

| model                          |       size |     params | backend    | ngl | test       |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ---------- | ---------------: |
| llama 8x7B Q4_K - Medium       |  26.49 GiB |    46.70 B | Metal      |  99 | pp 512     |    253.06 ± 1.82 |
| llama 8x7B Q4_K - Medium       |  26.49 GiB |    46.70 B | Metal      |  99 | pp 1024    |    253.27 ± 0.40 |
| llama 8x7B Q4_K - Medium       |  26.49 GiB |    46.70 B | Metal      |  99 | pp 2048    |    252.66 ± 0.16 |
| llama 8x7B Q4_K - Medium       |  26.49 GiB |    46.70 B | Metal      |  99 | pp 4096    |    250.42 ± 0.35 |
| llama 8x7B Q4_K - Medium       |  26.49 GiB |    46.70 B | Metal      |  99 | pp 8192    |    245.43 ± 0.56 |
| llama 8x7B Q4_K - Medium       |  26.49 GiB |    46.70 B | Metal      |  99 | tg 512     |     46.45 ± 0.08 |
| llama 8x7B Q4_K - Medium       |  26.49 GiB |    46.70 B | Metal      |  99 | tg 1024    |     45.37 ± 0.33 |
| llama 8x7B Q4_K - Medium       |  26.49 GiB |    46.70 B | Metal      |  99 | tg 2048    |     43.40 ± 0.92 |
| llama 8x7B Q4_K - Medium       |  26.49 GiB |    46.70 B | Metal      |  99 | tg 4096    |     40.27 ± 0.85 |
| llama 8x7B Q4_K - Medium       |  26.49 GiB |    46.70 B | Metal      |  99 | tg 8192    |     36.31 ± 0.26 |

**Comment by XiongjieDai** [comment]
Hi @adriangalilea, I have updated the results for Mac on LLaMA 3 in the benchmarks section, from 8GB M1 to 192GB M2 Ultra. I hope you can find similar specs with your machine :)

**Comment by XiongjieDai** [comment]
Completed. Check out the latest benchmarks forks!
