### ISSUE TITLE
Apple Silicon boosted by new macOS "Sequoia" - update required!

### ISSUE THREAD

**Issue by bluemoehre** [XiongjieDai/GPU-Benchmarks-on-LLM-Inference#17]
Great comparison - many thanks.

Would like to see updated numbers for the M1/M2/M3 chips, because I noticed a huge boost with the latest updates.

Sonoma vs. Sequoia on my MacBook Air M2:

<img width="999" alt="Bildschirmfoto 2024-10-11 um 16 20 08" src="https://github.com/user-attachments/assets/876a58a7-de58-4e23-a5ca-12b66cad9df8">

**Comment by XiongjieDai** [comment]
Hi,

Thank you for your info. llama.cpp uses Metal as the backend for Apple silicon, which runs the model on GPU, not the Neural Engine.

**Comment by bluemoehre** [comment]
My bad, I totally missed that while being excited about the new stats. Unfortunately I don't have a screenshot comparison of the GPU. But subjectively Ollama app is a lot faster as well. (Well, there is still the possibility that I simply had a problem with the old OS.)
