### ISSUE TITLE
Why is A6000 better than ada in table?

### ISSUE THREAD

**Issue by Phate334** [XiongjieDai/GPU-Benchmarks-on-LLM-Inference#2]
1. Do these two GPUs refer to RTX A6000 and RTX 6000 Ada? The ada model should be newer and it’s more expensive on RunPod, why is it slower?
    - [RTX A6000 vs RTX 6000 Ada](https://www.topcpu.net/en/gpu-c/rtx-a6000-vs-rtx-6000-ada)
    - [RunPod pricing](https://www.runpod.io/gpu-instance/pricing)
    - Average eval time (ms/token) by GPUs.

<html><body>

GPU | 7B_q4_0 | 7B_f16 | 65B_q4_0 | 65B_f16
-- | -- | -- | -- | --
A6000 48GB | 9.61 | 23.23 | 70.48 | OOM
A6000ada 48GB | 51.04 | 166.29 | 736.06 | OOM

</body>
</html>

2. Although using multiple GPUs in the table allows for running larger models, it actually results in slower performance. Is this due to a bottleneck in data transfer, or can be improved through software optimization?

<html><body>

GPU | 7B_q4_0 | 7B_f16 | 65B_q4_0 | 65B_f16
-- | -- | -- | -- | --
3090 24GB | 8.83 | 19.55 | OOM | OOM
4090 24GB | 7.24 | 16.83 | OOM | OOM
3090 24GB * 2 | 17.95 | 22.69 | 66.94 | OOM
4090 24GB * 2 | 16.24 | 21.61 | 62.54 | OOM

</body>
</html>

**Comment by XiongjieDai** [comment]
@Phate334 Hi Phate, thank you for your questions! 

For the first one, the results on RTX 6000 Ada also look weird to me. RTX 6000 Ada has a similar bandwidth and the same architecture as 4090; we should expect the performance to be as good as 4090 at least. I suppose this is a new professional computing card, and CUDA has not fully adapted to this graphics card yet.
<img width="2235" alt="Pasted Graphic 8" src="https://github.com/XiongjieDai/GPU-Benchmarks-on-LLM-Inference/assets/53258114/053018e2-181f-473c-a707-d6bbe573af33"> (I have checked that the data was successfully loaded on the graphics card at that time)

For the second, the bottleneck in data transfer matters when we are doing inference. We can only get 128GB/s on the latest PCIe 5.0, and this is far less than normal bandwidth, like over 1TB/s on 4090. When using multiple GPUs, we will not fully utilize them. We can simply ban the unnecessary GPUs to save time on data transfer if we don't need the extra GPU memory.
<img width="2231" alt="Pasted Graphic" src="https://github.com/XiongjieDai/GPU-Benchmarks-on-LLM-Inference/assets/53258114/1a2f9b06-dab2-4dcb-a241-f808957e05c6">
<img width="2231" alt="Pasted Graphic 1" src="https://github.com/XiongjieDai/GPU-Benchmarks-on-LLM-Inference/assets/53258114/58a13122-4ec2-4867-bd97-e94f25564f26">

**Comment by Phate334** [comment]
> I suppose this is a new professional computing card, and CUDA has not fully adapted to this graphics card yet. 

I found a similar [discussion](https://forums.developer.nvidia.com/t/rtx-6000-ada-slower-than-geforce-rtx-3050-in-python-with-tensorflow-2/265260) on NVIDIA community.

> This GPU has compute capability 8.9 and CUDA 11.8 should support it. However, you would want to find out whether the CUDA-accelerated software you are using includes SASS (machine code) for sm_89 in the fat binary, otherwise there will be overhead for JIT compilation. You may find out that you must build some or all of the software from source code to include sm_89 support.

But I don't know how to check this on RunPod, maybe 6000 ada is not a good choice for now.

Thank you for your help! This repo is awesome.
