### ISSUE TITLE
Request to Add TTFT Metrics to Benchmark Results

### ISSUE THREAD

**Issue by rafklu** [XiongjieDai/GPU-Benchmarks-on-LLM-Inference#4]
Hey @XiongjieDai

I've been diving into your GPU Benchmarks on LLM Inference repo, and it's super helpful for figuring out the best hardware for running LLMs. Awesome work!

Any chance you could add TTFT (Time-To-First-Token) metrics to the benchmarks? 

Thanks a ton for considering it! Keep up the great work.

Cheers,
Rafał

**Comment by XiongjieDai** [comment]
> Hey @XiongjieDai
> 
> I've been diving into your GPU Benchmarks on LLM Inference repo, and it's super helpful for figuring out the best hardware for running LLMs. Awesome work!
> 
> Any chance you could add TTFT (Time-To-First-Token) metrics to the benchmarks?
> 
> Thanks a ton for considering it! Keep up the great work.
> 
> Cheers, Rafał

Hi @rafklu 

Thank you for your interest!

I do think Time-To-First-Token is a good point. I suppose you should consider both the model loading time and the prompt evaluating time. When you start the conversation, you will need to load your model from your disk to the GPU. The model loading time will be your SSD speed bounded. After you load your model on the GPU, you will only need to consider the prompt evaluating speed on your following conversation. The prompt evaluating speed is more GPU performance-related.

Sorry, I didn't test the SSD speed when I rented the GPU. But you can still check my results documents for the model loading time for reference. All I would say use the best NVME SSD to boost the first time you load the model.

Good luck and have fun!

Best,
Xiongjie
